### ISSUE TITLE
Server returns 500 when device name contains right single quotation mark (U+2019)

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#138]
Right single quotation mark as like in `Matthew’s MacBook Pro`.

<img width="839" alt="screen shot 2017-03-21 at 9 12 05 pm" src="https://cloud.githubusercontent.com/assets/13400887/24177869/a8be58a0-0e7b-11e7-8e30-e3dcaa2533d8.png">
<img width="840" alt="screen shot 2017-03-21 at 9 12 51 pm" src="https://cloud.githubusercontent.com/assets/13400887/24177870/a8c19358-0e7b-11e7-866e-40a8f0cbf155.png">

**Comment by ClaytonPassmore** [comment]
😭
