### ISSUE TITLE
Add some quality public decks for TAs and Prof

### ISSUE THREAD

**Issue by ClaytonPassmore** [ClaytonPassmore/ProjectOrange#169]
If we all add like 3 decent decks and make them public, I think the profs and TAs will get a lot of value out of it when they're testing/when we're demo-ing.

The decks can be about whatever you want.

Once we do that, everyone should randomly rate the decks so we get some rating data... Should make discover slightly more interesting.

**Comment by mattyu007** [comment]
Quality decks have been achieved ✅
