### ISSUE TITLE
Flag card endpoint returns 404 on deleted deck

### ISSUE THREAD

**Issue by Tyler-Brenneman** [ClaytonPassmore/ProjectOrange#186]
If a deck was deleted on a different device and you try to sync a card flag, the flag endpoint will return 404 error.

Expected behaviour: flag endpoint should return 409 status like edit endpoint

![image](https://cloud.githubusercontent.com/assets/6018963/24328418/3814eac6-11b7-11e7-841d-fa3f3dff1920.png)

![image](https://cloud.githubusercontent.com/assets/6018963/24328401/c227f826-11b6-11e7-8b3d-8891c0a5f81b.png)

@ClaytonPassmore 
@henryc132

**Comment by Tyler-Brenneman** [comment]
If this situation happens the client should just remove the deck from `decks`?

**Comment by ClaytonPassmore** [comment]
I think the expectation is that they should still get the "This deck has been deleted, do you want to make a copy" flow, but the pending card flags should just be dropped

**Comment by Tyler-Brenneman** [comment]
Ohh I see. Does that prompt happen for private decks that have been deleted on another device? I thought that prompt was only for deleted remote decks.

**Comment by mattyu007** [comment]
I believe that flow is only implemented for

1. decks which are deleted but not removed from the library (i.e., a shared or public deck is deleted by the owner)
2. decks which become inaccessible (i.e., sharing settings for a shared or public deck are downgraded by the owner)

**Comment by ClaytonPassmore** [comment]
Yeah sorry, you're both right.

I think if the user has deleted their own deck, any pending changes to flagged cards should be dropped. If they deleted it, they should have the expectation that they won't have access to it, and thus cannot flag it.
