### ISSUE TITLE
Avoid calling Create Deck and Edit Deck API for simple deck creates

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#208]
Right now, when a deck is created, we call the Create Deck API first, and then call the Edit Deck API to sync card changes and other deck properties.

For simple deck adds (i.e., only adding cards and leaving the deck as private), we can just pass the cards to the Create Deck API and avoid calling the Edit Deck API.

**Comment by ClaytonPassmore** [comment]
Seems hard. Closing for now.
