### ISSUE TITLE
Add support for automatically triggering library sync

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#28]
Currently the app only supports manually triggering sync by pulling down on the Library home screen. We need to add support for automatically syncing the library at appropriate times, including:
1. When the app is launched
2. When the device transitions from offline to online
3. Potentially when the user returns to the Library home screen by popping the Navigator stack?

---------
## Previous issue
The local data set should be refreshed when the main Library screen comes to the foreground. That is:

1. when the Library screen is shown for the first time (after login or when the app is started)
2. when in-tab navigation pops enough scenes to returns to the Library screen
3. when the Library tab is selected in the tab bar / drawer menu

**1** and **2** can be captured by hooking into the `Component` lifecycle and into the `Navigator`'s navigation context in `LibraryHome.js`:

```js
_navigationEventListenerToken: any

_navigationEventListener(event) {
  // The top-level route is just {}
  if (Object.keys(event.data.route).length === 0) {
    // ** REFRESH ** //
  }
}

componentDidMount() {
  this._navigationEventListenerToken =
    this.props.navigator.navigationContext.addListener('didfocus', this._navigationEventListener)
}

componentWillReceiveProps(nextProps: Props) {
  if (nextProps.navigator !== this.props.navigator) {
    this._navigationEventListenerToken.remove()
    this._navigationEventListenerToken =
      nextProps.navigator.navigationContext.addListener('didfocus', this._navigationEventListener)
  }
}

componentWillUnmount() {
  this._navigationEventListenerToken.remove()
}
```

**3** is TBD, but perhaps we can hook into the `tabs` actions.

**Comment by ClaytonPassmore** [comment]
@mattyu007 do we still want this in addition to the manual refresh?

**Comment by mattyu007** [comment]
@ClaytonPassmore It might not be necessary, though we should do a sync when the app is brought to the foreground.
