### ISSUE TITLE
Display deck owner name once server starts returning owner name in deck metadata response

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#48]
Currently in the app for shared and public decks not owned by the user, we just display a generic string "someone else" in place of an actual person name. Once #47 is in, we can replace the generic string with the actual name of the deck owner.

![img_1666](https://cloud.githubusercontent.com/assets/13400887/23528627/86603cd2-ff68-11e6-812b-34bd91372aae.PNG)

**Comment by ClaytonPassmore** [comment]
#47 is in but note that the author can be null, so you may want to use this generic string for that scenario
