### ISSUE TITLE
Add ability to delete decks from Library

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#63]
On both iOS and Android, this feature is accessible by entering some kind of edit mode for the list.

At this time we are not supporting drag and drop to rearrange decks.

UX Reference:
![cue ux mocks 005](https://cloud.githubusercontent.com/assets/13400887/23690110/225f2ed6-038d-11e7-91d0-035f01d02dba.png)
![cue ux mocks 006](https://cloud.githubusercontent.com/assets/13400887/23690111/22695000-038d-11e7-8a83-aa917bf9a4c4.png)

**Comment by ClaytonPassmore** [comment]
@mattyu007 currently there is no concept of deck order on the server

**Comment by mattyu007** [comment]
@ClaytonPassmore Alright, I've updated the issue.
