### ISSUE TITLE
Add Deck View edit mode

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#64]
In Deck View edit mode, users can delete, rearrange, and enter the Edit Deck flow (#60).

UX Reference:
![cue ux mocks 010](https://cloud.githubusercontent.com/assets/13400887/23690157/6dfe216c-038d-11e7-80ed-b53a0984e651.png)
![cue ux mocks 011](https://cloud.githubusercontent.com/assets/13400887/23690158/6e06e78e-038d-11e7-9cb5-d2e66d20f16c.png)

**Comment by Tyler-Brenneman** [comment]
issue #103 will need to be resolved for card position changes to be handled correctly.

When changing position of a single card, only pass in the updated position of that card. The library reducer should handle updating the positions of all the other cards.

**Comment by mattyu007** [comment]
This is currently blocked until #97 is merged since it massively overhauls `DeckView`.

**Comment by mattyu007** [comment]
Side note: This may remove the collapsing header we currently have in Deck View, we may consider re-adding it later using a different method. https://medium.com/appandflow/react-native-collapsible-navbar-e51a049b560a
