### ISSUE TITLE
Can't refresh library if library is empty

### ISSUE THREAD

**Issue by Tyler-Brenneman** [ClaytonPassmore/ProjectOrange#91]
@ClaytonPassmore 

found this while creating new decks

**Comment by mattyu007** [comment]
This should be because we only render an `EmptyView` and don't actually render the `ListView` component at all if there aren't any decks to show. Probably need to see if we can show `EmptyView` behind the empty `ListView`.

**Comment by ClaytonPassmore** [comment]
Mmmm yup this makes sense. I'll take a look.
