### ISSUE TITLE
Deck inset in library can overlap text content at small screen sizes

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#92]
At small screen sizes (e.g., iPhone 5s), the deck inset can overlap the deck title.

As I see it, there are two solutions:

1. Make the deck name text background colour transparent, or
2. Set the z-index of the deck inset higher so it is laid out on top of the text

![img_0003](https://cloud.githubusercontent.com/assets/13400887/23887327/742cf9c2-0857-11e7-8e5b-ce0155674073.PNG)

**Comment by ClaytonPassmore** [comment]
@mattyu007 I personally feel like the `zIndex` solution would look nice, thoughts?

**Comment by mattyu007** [comment]
@ClaytonPassmore 🤷🏻‍♂️ I don't feel strongly about either.
