### ISSUE TITLE
Actually flag cards in Play Deck when cards are swiped up

### ISSUE THREAD

**Issue by mattyu007** [ClaytonPassmore/ProjectOrange#96]
Right now the swipe up gesture just moves to the next card without firing off any actions.

Also consider indicating on the card itself whether it is flagged or not.

**Comment by Tyler-Brenneman** [comment]
Should just be able to call action `editDeck({uuid: deckuuid, cards: [{action: 'edit', uuid: cardUuid, needs_review: true|false }]}`
